

path: C:/Users/pt19100041.BIUST/Desktop/conference tracker 1/data3/  # dataset root dir


train: train/images  # train images (relative to 'path')
val: val/images  # val images (relative to 'path')

# Classes
names:
  0: Black rhino left
  1: Black rhino right
  2: Blue wildebeest left
  3: Blue wildebeest right
  4: Giraffe left
  5: Giraffe right
  6: White rhino left
  7: White rhino right
